blogapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
   path('users',include('usersapp.urls')),
   path('',include('blogpost.urls'))
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogpost/urls.py
from django.urls import path

from . import views

app_name='blogpost'

urlpatterns = [
	path('',views.home,name='home'),
    path('cate/<str:cats>/',views.categories,name='categories'),
    path('subscribenow',views.subscribenow,name='subscribenow'),
    path('addblog',views.addblog,name='addblog'),
    path('addcategory/',views.addcategory,name='addcategory'),
    path('<int:pk>/',views.details,name='details'),
]

usersapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
#from django.contrib.auth.views import logout
from . import views
from .forms import LoginForm
app_name='usersapp'
# https://magspot-simple.blogspot.com/
urlpatterns = [
	path('',views.signup,name='signup'),
    path('signin/',auth_views.LoginView.as_view(template_name='pages/signin.html',authentication_form=LoginForm),name='signin'),
    path('userlogout/',views.userlogout,name='userlogout'),
]

blogpost/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
# Create your models here.
# category model
class Category(models.Model):
    name=models.CharField(max_length=200,unique=True)
    def __str__(self):
        return self.name
        

# post model
class Post(models.Model):
    title=models.TextField(max_length=100)
    category=models.ForeignKey(Category,related_name='category',on_delete=models.CASCADE)
    created_by=models.ForeignKey(User,related_name='user',on_delete=models.CASCADE)
    post=models.TextField()
    image=models.ImageField(upload_to='post_images',blank=True)
    created_at=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.created_by.username
    
# comment
class Comment(models.Model):
    post_id=models.ForeignKey(Post,related_name='posts',on_delete=models.CASCADE)
    comment=models.TextField()
    user=models.ForeignKey(User,related_name='users',on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username
    


# subscrips
class Subscribe(models.Model):
    newslatter=models.EmailField()
    def __str__(self):
        return self.newslatter

usersapp/models.py
from django.db import models

blogpost/forms.py
from django import forms

from .models import Category,Post,Subscribe

class Addcategory(forms.ModelForm):
    class Meta:
        model=Category
        fields=('name',)
        name=forms.CharField(widget=forms.TextInput(attrs={'placeholder':"category"}))


# post forms
class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=('category','post','title','image')
        title=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Blog title'}))
        category=forms.CharField(widget=forms.Select(attrs={'Placeholder':'Select'}))
        post=forms.CharField(widget=forms.Textarea(attrs={'Placeholder':'Write your blog'}))
        image=forms.CharField(widget=forms.ImageField())



# subscribe

class NewslatterForm(forms.ModelForm):
    class Meta:
        model=Subscribe
        fields=('newslatter',)
        newslatter=forms.CharField(widget=forms.EmailField)

usersapp/forms.py
from django import forms 
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm

class SingupForm(UserCreationForm):
    class Meta:
        model=User 
        fields=('username','email','password1','password2')
        username=forms.CharField(label='search',widget=forms.TextInput(attrs={'placeholder': 'User name'}))
        email=forms.CharField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
        password1=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
        password2=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'confirm password'}))
        
       

# login
class LoginForm(AuthenticationForm):
    username=forms.CharField(required=True,widget=forms.TextInput(attrs={'placeholder':'username'}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'password'}))

blogpost/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import Addcategory,PostForm,NewslatterForm
from django.contrib.auth.decorators import login_required
from .models import Post,Category

# Create your views here.
def home(request):
    post=Post.objects.all()
    categories=Category.objects.all()
    subscribe=NewslatterForm()
    return render(request,'post/home.html',{
           'post':post,'title':'blog page','subscribe':subscribe,
           'categories':categories
	})


def addcategory(request):
        if request.method=="POST":
              categoryform=Addcategory(request.POST)
              if categoryform.is_valid():
                    categoryform.save()
                    return redirect('blogpost:addcategory')
        else:
                categoryform=Addcategory()
                return render(request,'admin/addcategory.html',{
              'title':'Add Category','categoryform':categoryform
	})
        
# code to add blogs
@login_required
def addblog(request):
      if request.method=="POST":
            
            postform=PostForm(request.POST, request.FILES)
            if postform.is_valid():
                  blog=postform.save(commit=False)
                  blog.created_by=request.user
                  blog.save()
                  return redirect('blogpost:addblog')
      else:
                postform=PostForm()
                return render(request,'post/addblog.html',{
            'title':'Add blog','postform':postform
	  })

# getting categories

def categories(request,cats):
       postcat=Post.objects.filter(category=cats)
       #print(postcat)
       return render(request,'post/categories.html',{
              'postcat':postcat,'title':'Category'
       })

# details page
def details(request,pk):
       getpost=get_object_or_404(Post,pk=pk)
       categories=Category.objects.all()
       print(getpost.id) 
       return render(request,'post/details.html',{
              'getpost':getpost,'categories':categories
       })
# subscription backend
def subscribenow(request):
       if request.method=="POST":
              subscribe=NewslatterForm(request.POST)
              if subscribe.is_valid():
                     subscribe.save()
                     return redirect('blogpost:home')

usersapp/views.py
from django.shortcuts import render,redirect
from .forms import SingupForm, LoginForm
# Create your views here.
from django.contrib.auth import logout
from django.contrib import messages
#from django.http import HttpResponseRedirect

def signup(request):
    if request.method=='POST':
       
        signupforms=SingupForm(request.POST)
       
        if signupforms.is_valid():
            #print('hi yes pass v')
            signupforms.save()
            print('saved')
            return redirect('usersapp:index')
    else:
        signupforms=SingupForm()
    return render(request,'pages/signup.html',{
        'signupforms':signupforms,'title':'Singup'
	})

def userlogout(request):
    logout(request)
    messages.success(request,('you are logout'))
    #return  redirect('usersapp:index')
    return redirect('usersapp:signup')

blogpost/templates/post/addblog.html
{% extends 'layout/based.html' %}

{% block title %}{{title}}{% endblock  %}


{% block content %}
<div class="addblogpage">
	<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<label for="">Blog Titel</label>
		{{postform.title}}
		<label for="">Blog Category</label>
		{{postform.category}}
		<label for="">Blog post</label>
		{{postform.post}}
		<label for="">Blog image</label>
		{{postform.image}}
		<button>Create</button>
	</form>
</div>
{% endblock  %}

blogpost/templates/post/categories.html
{% extends 'layout/based.html' %}
{% block title %}{{title}}{% endblock  %}

{% block content %}
<div class="homepage">
	<div class="container_home">
		<section class="blogpostcontainer">
			<div class="maincontentholder">
		{% for p in postcat %}
		<a href="">
			
				<div class="postholder">
					{% if p.image %}
					<div class="blogimgdiv" style="background-image: url({{ p.image.url }});">
						
					</div>
				{% endif %}
					
			<div class="blog_holderdv">
				<h1>{{p.title}}</h1>
				<p>{{ p.post|stringformat:".100s" }}</p>
			</div>
				</div>
		</a>
		{% endfor %}
			
		</div>
		</section>
{% comment %} END OF MAINCONTENT {% endcomment %}
		<section class="leftbar">
		<div class="social_media">
			<h1>Follow us on social media</h1>
			<div class="socialline">
				<div class="sociallineinner"></div>
			</div>
			{% comment %} social media {% endcomment %}
			<div class="iconholder">
				<div class="icons">
					<div class="iconsdiv facebook">
					<a href="">
						<i class="fa fa-facebook-square" style="font-size:25px"></i>
					<h3>Facebook</h3>
					</a>
				</div>
				<div class="iconsdiv twitter">
					<a href="">
						<i class="fa fa fa-twitter-square" style="font-size:25px"></i>
					<h3>Twitter</h3>
					</a>
				</div>
				<div class="iconsdiv instagram">
					<a href="">
						<i class="fa fa fa fa-instagram" style="font-size:25px"></i>
					<h3>Instagram</h3>
					</a>
				</div>
				<div class="iconsdiv youtube">
					<a href="">
						<i class="fa fa 	fa fa-youtube-play" style="font-size:25px"></i>
					<h3>Youtube</h3>
					</a>
				</div>
				</div>
			</div>
		</div>
			{% comment %} the end {% endcomment %}
		<div class="newslatterdivider"></div>
		{% comment %} subscribe forms {% endcomment %}
		<form action="{% url 'blogpost:subscribenow' %}" class="subscribeform" method="post">
			{% csrf_token %}
			<p>Subscribe to our mailing list to get the new updates.</p>
			{{subscribe.newslatter}}
			<button>Subscrib</button>
		</form>
		{% comment %} the end {% endcomment %}
		{% comment %} categories {% endcomment %}
		<div class="category">
			<div class="newslatterdivider categorydidver">
				<div class="catedidvercolor"></div>
			</div>
			
				{% for c in categories %}
				<a href="" class="categorylink">
					<h3>{{c.name}}</h3>
					<small>({{c.category.count}})</small>
				
				</a>
			
			{% endfor %}
		
			
		</div>
		{% comment %} the end of categories {% endcomment %}
	</section>
	{% comment %} end of sidebar {% endcomment %}
	</div>
	
</div>
{% endblock  %}

blogpost/templates/post/details.html
{% extends 'layout/based.html' %}
{% block title %}{{getpost.title}}{% endblock  %}

{% block content %}
<div class="homepage">
	<div class="container_home">
		<section class="blogpostcontainer">
			<div class="maincontentholderdetails">
	
		
			
				<div class="postholderdetails">
					{% if getpost.image %}
					<div class="blogimgdivdetails" style="background-image: url({{ getpost.image.url }});">
						
					</div>
				{% endif %}
					
			<div class="blog_holderdvdetails">
				<h1>{{getpost.title}}</h1>
				<p>{{ getpost.post }}</p>
			</div>
				</div>
		
		
			
		</div>
		</section>
{% comment %} END OF MAINCONTENT {% endcomment %}
		<section class="leftbar">
		<div class="social_media">
			<h1>Follow us on social media</h1>
			<div class="socialline">
				<div class="sociallineinner"></div>
			</div>
			{% comment %} social media {% endcomment %}
			<div class="iconholder">
				<div class="icons">
					<div class="iconsdiv facebook">
					<a href="">
						<i class="fa fa-facebook-square" style="font-size:25px"></i>
					<h3>Facebook</h3>
					</a>
				</div>
				<div class="iconsdiv twitter">
					<a href="">
						<i class="fa fa fa-twitter-square" style="font-size:25px"></i>
					<h3>Twitter</h3>
					</a>
				</div>
				<div class="iconsdiv instagram">
					<a href="">
						<i class="fa fa fa fa-instagram" style="font-size:25px"></i>
					<h3>Instagram</h3>
					</a>
				</div>
				<div class="iconsdiv youtube">
					<a href="">
						<i class="fa fa 	fa fa-youtube-play" style="font-size:25px"></i>
					<h3>Youtube</h3>
					</a>
				</div>
				</div>
			</div>
		</div>
			{% comment %} the end {% endcomment %}
		<div class="newslatterdivider"></div>
		{% comment %} subscribe forms {% endcomment %}
		<form action="{% url 'blogpost:subscribenow' %}" class="subscribeform" method="post">
			{% csrf_token %}
			<p>Subscribe to our mailing list to get the new updates.</p>
			{{subscribe.newslatter}}
			<button>Subscrib</button>
		</form>
		{% comment %} the end {% endcomment %}
		{% comment %} categories {% endcomment %}
		<div class="category">
			<div class="newslatterdivider categorydidver">
				<div class="catedidvercolor"></div>
			</div>
			
				{% for c in categories %}
				<a href="" class="categorylink">
					<h3>{{c.name}}</h3>
					<small>({{c.category.count}})</small>
				
				</a>
			
			{% endfor %}
		
			
		</div>
		{% comment %} the end of categories {% endcomment %}
	</section>
	{% comment %} end of sidebar {% endcomment %}
	</div>
	
</div>
{% endblock  %}

blogpost/templates/post/home.html
{% extends 'layout/based.html' %}
{% block title %}{{title}}{% endblock  %}

{% block content %}
<div class="homepage">
	<div class="container_home">
		<section class="blogpostcontainer">
			<div class="maincontentholder">
		{% for p in post %}
		<a href="{% url 'blogpost:details' p.id %}">
			
				<div class="postholder">
					{% if p.image %}
					<div class="blogimgdiv" style="background-image: url({{ p.image.url }});">
						
					</div>
				{% endif %}
					
			<div class="blog_holderdv">
				<h1>{{p.title}}</h1>
				<p>{{ p.post|stringformat:".100s" }}</p>
			</div>
				</div>
		</a>
		{% endfor %}
			
		</div>
		</section>
{% comment %} END OF MAINCONTENT {% endcomment %}
		<section class="leftbar">
		<div class="social_media">
			<h1>Follow us on social media</h1>
			<div class="socialline">
				<div class="sociallineinner"></div>
			</div>
			{% comment %} social media {% endcomment %}
			<div class="iconholder">
				<div class="icons">
					<div class="iconsdiv facebook">
					<a href="">
						<i class="fa fa-facebook-square" style="font-size:25px"></i>
					<h3>Facebook</h3>
					</a>
				</div>
				<div class="iconsdiv twitter">
					<a href="">
						<i class="fa fa fa-twitter-square" style="font-size:25px"></i>
					<h3>Twitter</h3>
					</a>
				</div>
				<div class="iconsdiv instagram">
					<a href="">
						<i class="fa fa fa fa-instagram" style="font-size:25px"></i>
					<h3>Instagram</h3>
					</a>
				</div>
				<div class="iconsdiv youtube">
					<a href="">
						<i class="fa fa 	fa fa-youtube-play" style="font-size:25px"></i>
					<h3>Youtube</h3>
					</a>
				</div>
				</div>
			</div>
		</div>
			{% comment %} the end {% endcomment %}
		<div class="newslatterdivider"></div>
		{% comment %} subscribe forms {% endcomment %}
		<form action="{% url 'blogpost:subscribenow' %}" class="subscribeform" method="post">
			{% csrf_token %}
			<p>Subscribe to our mailing list to get the new updates.</p>
			{{subscribe.newslatter}}
			<button>Subscrib</button>
		</form>
		{% comment %} the end {% endcomment %}
		{% comment %} categories {% endcomment %}
		<div class="category">
			<div class="newslatterdivider categorydidver">
				<div class="catedidvercolor"></div>
			</div>
			
				{% for c in categories %}
				<a href="{% url 'blogpost:categories' c.id %}" class="categorylink">
					<h3>{{c.name}}</h3>
					<small>({{c.category.count}})</small>
				
				</a>
			
			{% endfor %}
		
			
		</div>
		{% comment %} the end of categories {% endcomment %}
	</section>
	{% comment %} end of sidebar {% endcomment %}
	</div>
	
</div>
{% endblock  %}

usersapp/templates/layout/based.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}{% endblock  %}</title>
	<link rel="stylesheet" href="{% static 'css/forms.css' %}">
	<link rel="stylesheet" href="{% static 'css/nav.css' %}">
	<link rel="stylesheet" href="{% static 'css/postcss.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="{% static 'css/mediaquery.css' %}">
</head>
<body>
	{% include 'layout/navbar.html' %}
	{% block content %}{% endblock  %}
	 {% include 'layout/footer.html' %} 
</body>
</html>

usersapp/templates/layout/footer.html
<footer>
	<div class="footercontainer">
		<div class="ownner">Bright C Web Developer</div>
		<div class="aboutus">
			<p>Bight C Web Developer is young man who loves creativity</p> 
		</div>
		<div class="footericon">
		<div class="">
					<a href="">
						<i class="fa fa-facebook-square" style="font-size:25px"></i>
					<h3>Facebook</h3>
					</a>
				</div>
				<div class="">
					<a href="">
						<i class="fa fa fa-twitter-square" style="font-size:25px"></i>
					<h3>Twitter</h3>
					</a>
				</div>
				<div class="">
					<a href="">
						<i class="fa fa fa fa-instagram" style="font-size:25px"></i>
					<h3>Instagram</h3>
					</a>
				</div>
				<div class="">
					<a href="">
						<i class="fa fa 	fa fa-youtube-play" style="font-size:25px"></i>
					<h3>Youtube</h3>
					</a>
				</div>
		</div>
	</div>
</footer>

usersapp/templates/layout/navbar.html
<nav class="nav">
	{% load static %}
	<a class="sitelogo" href="">
		<img src="{% static 'logo/mylogo.jpg' %}" alt="">
	</a>
	<ul>
		<li><a href="/">Home</a></li>
		
		{% if user.is_authenticated %}
		<li><a href="{% url 'blogpost:addcategory' %}">Add Category</a></li>
		<li><a href="{% url 'blogpost:addblog' %}">Add blog</a></li>
			<li><a href="{% url 'usersapp:userlogout' %}">Logout</a></li>
			{% else %}
			<li><a href="{% url 'usersapp:signin' %}">Login</a></li>
			<li><a href="{% url 'usersapp:signup' %}">Register</a></li>
		{% endif %}
			
		
		
	</ul>
</nav>

usersapp/templates/pages/signin.html
{% extends 'layout/based.html' %}

{% block title %}{{title}}{% endblock  %}

{% block content %}
<div class="singupdiv">
	<form action="" method="post">
		{% csrf_token %}
		
		<label for="">Email</label>
		{{form.username}}
		<label for="">Password</label>
		{{form.password}}
		
		<button type="submit">Signin</button>
		{% if form.errors or form.non_field_errors %}
		<div class="error">
			{% for field in form  %}
			{{field.errors}}
		{% endfor %}
		{{form.non_field_errors}}
		</div>
			
		{% endif %}
	</form>
</div>

{% endblock  %}

usersapp/templates/pages/signup.html
{% extends 'layout/based.html' %}

{% block title %}{{title}}{% endblock  %}

{% block content %}
<div class="singupdiv">
	<form action="" method="post">
		{% csrf_token %}
		<label for="">User name</label>
		{{signupforms.username}}
		<label for="">Email</label>
		{{signupforms.email}}
		<label for="">Password</label>
		{{signupforms.password1}}
		<label for="">Confirm password</label>
		{{signupforms.password2}}

		<button type="submit">Signup</button>
		{% if signupforms.errors or signupforms.non_field_errors %}
		<div class="error">
			{% for field in signupforms  %}
			{{field.errors}}
		{% endfor %}
		{{signupforms.non_field_errors}}
		</div>
			
		{% endif %}
	</form>
</div>

{% endblock  %}